<template>
    <div>
        <section class="section pb-0 bg-gradient-warning">
            <div class="container">
                <div class="row row-grid align-items-center">
                <div class="col-md-6 order-lg-2 ml-lg-auto">
                    <div class="position-relative pl-md-5">

                    <img :src="'/assets/img/ill/ill-2.svg'" class="img-center img-fluid" alt="image">
                    </div>
                </div>
                <div class="col-lg-6 order-lg-1">
                    <div class="d-flex px-3">
                    <div>
                        <div class="icon icon-lg icon-shape bg-gradient-white shadow rounded-circle text-primary">
                        <i class="ni ni-building text-primary"></i>
                        </div>
                    </div>
                    <div class="pl-4">
                        <h4 class="display-3 text-white">Modern Interface</h4>
                        <p class="text-white">The Arctic Ocean freezes every winter and much of the sea-ice then thaws every summer, and that process will continue whatever.</p>
                    </div>
                    </div>
                    <div class="card shadow shadow-lg--hover mt-5">
                    <div class="card-body">
                        <div class="d-flex px-3">
                        <div>
                            <div class="icon icon-shape bg-gradient-success rounded-circle text-white">
                            <i class="ni ni-satisfied"></i>
                            </div>
                        </div>
                        <div class="pl-4">
                            <h5 class="title text-success">Awesome Support</h5>
                            <p>The Arctic Ocean freezes every winter and much of the sea-ice then thaws every summer, and that process will continue whatever.</p>
                            <a href="#" class="text-success">Learn more</a>
                        </div>
                        </div>
                    </div>
                    </div>
                    <div class="card shadow shadow-lg--hover mt-5">
                    <div class="card-body">
                        <div class="d-flex px-3">
                        <div>
                            <div class="icon icon-shape bg-gradient-warning rounded-circle text-white">
                            <i class="ni ni-active-40"></i>
                            </div>
                        </div>
                        <div class="pl-4">
                            <h5 class="title text-warning">Modular Components</h5>
                            <p>The Arctic Ocean freezes every winter and much of the sea-ice then thaws every summer, and that process will continue whatever.</p>
                            <a href="#" class="text-warning">Learn more</a>
                        </div>
                        </div>
                    </div>
                    </div>
                </div>
                </div>
            </div>
            <!-- SVG separator -->
            <div class="separator separator-bottom separator-skew zindex-100">
                <svg x="0" y="0" viewBox="0 0 2560 100" preserveAspectRatio="none" version="1.1" xmlns="http://www.w3.org/2000/svg">
                <polygon class="fill-white" points="2560 0 2560 100 0 100"></polygon>
                </svg>
            </div>
        </section>

        <section class="section section-lg">
            <div class="container">
                <div class="row row-grid align-items-center">
                <div class="col-md-6 order-md-2">
                    <img :src="'/assets/img/theme/promo-1.png'" class="img-fluid floating" alt="image">
                </div>
                <div class="col-md-6 order-md-1">
                    <div class="pr-md-5">
                    <div class="icon icon-lg icon-shape icon-shape-success shadow rounded-circle mb-5">
                        <i class="ni ni-settings-gear-65"></i>
                    </div>
                    <h3>Awesome features</h3>
                    <p>The kit comes with three pre-built pages to help you get started faster. You can change the text and images and you're good to go.</p>
                    <ul class="list-unstyled mt-5">
                        <li class="py-2">
                        <div class="d-flex align-items-center">
                            <div>
                            <div class="badge badge-circle badge-success mr-3">
                                <i class="ni ni-settings-gear-65"></i>
                            </div>
                            </div>
                            <div>
                            <h6 class="mb-0">Carefully crafted components</h6>
                            </div>
                        </div>
                        </li>
                        <li class="py-2">
                        <div class="d-flex align-items-center">
                            <div>
                            <div class="badge badge-circle badge-success mr-3">
                                <i class="ni ni-html5"></i>
                            </div>
                            </div>
                            <div>
                            <h6 class="mb-0">Amazing page examples</h6>
                            </div>
                        </div>
                        </li>
                        <li class="py-2">
                        <div class="d-flex align-items-center">
                            <div>
                            <div class="badge badge-circle badge-success mr-3">
                                <i class="ni ni-satisfied"></i>
                            </div>
                            </div>
                            <div>
                            <h6 class="mb-0">Super friendly support team</h6>
                            </div>
                        </div>
                        </li>
                    </ul>
                    </div>
                </div>
                </div>
            </div>
        </section>
    </div>
</template>
